title: Hendra Praditya Ferdiansyah # your name (or website title) here
logo: "/images/hendra.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an undergraduate student of Information Systems at Universitas Negeri Semarang.
  <br><br>
  I am interested in website development, data science & analytics, and network engineering. 
  <br><br>
  <a href="https://www.linkedin.com/in/hendrafrs">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
